name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    image: alpine
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          uptime
          mkdir public
          apk add py3-pip && pip3 install --user markdown
          cat README.md >> tmp.md
          echo "" >> tmp.md
          echo "##Examples " >> tmp.md
          echo "" >> tmp.md
          echo "| Image | Status |" >> tmp.mkdir
          echo "|--|--|" >> tmp.md
          bash image-info.sh library/alpine >> tmp.md
          bash image-info.sh library/ubuntu >> tmp.md
          bash image-info.sh library/nginx  >> tmp.md
          echo "" >> tmp.md
          python3 -m markdown readme.md > public/index.html
          cp public/index.html public/404.html

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.